// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Orca.Orchestrator.Infrastructure;

#nullable disable

namespace Orca.Orchestrator.Infrastructure.Migrations
{
    [DbContext(typeof(OrchestratorContext))]
    [Migration("20260202144226_LaunchRetry")]
    partial class LaunchRetry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Orca.Orchestrator.Domain.Entities.JobExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AwxOoExecutionStatus")
                        .HasColumnType("text");

                    b.Property<string>("AwxOoJobId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("ExecutionPayload")
                        .HasColumnType("jsonb");

                    b.Property<string>("ExecutionResourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ExecutionResourceType")
                        .HasColumnType("integer");

                    b.Property<string>("ExecutionResponse")
                        .HasColumnType("jsonb");

                    b.Property<string>("ExecutionStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExecutionTargetType")
                        .HasColumnType("integer");

                    b.Property<string>("LastLaunchError")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastPolledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LaunchAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NextLaunchAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PollingAttempts")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SentToAwxOoAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AwxOoJobId");

                    b.HasIndex("ExecutionStatus");

                    b.HasIndex("RequestId");

                    b.ToTable("JobExecutions");
                });
#pragma warning restore 612, 618
        }
    }
}
